name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 1
      GAME_LANGUAGE: ENGLISH
      MODERN: 1
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout syms
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v5
        with:
          path: symbols
          ref: symbols

      - name: Checkout agbcc
        uses: actions/checkout@v5
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev
        # build-essential and git are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Modern
        run: make -j${nproc} all

      - name: Rename File pokeemerald_modern.gba
        run: mv pokeemerald_modern.gba "Pokemon Emerald (Modern).gba"

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Latest-Build
          path: |
            Pokemon Emerald (Modern).gba
          retention-days: 90
          if-no-files-found: error